### ISSUE TITLE
Clarification on documentation

### ISSUE THREAD

**Issue by matthew-dean** [oaleynik/nwjs-autoupdater#1]
I'm confused about this.

> The line `<requestedExecutionLevel level="asInvoker" uiAccess="false"/>` will allow your app to run updater on windows without admin rights. To embed this information in your updater's binary you need to use https://github.com/akavel/rsrc 

Are you saying you can't just use the build script? Some other action is needed with the output `.exe` file? If so, why?

**Comment by oaleynik** [comment]
@matthew-dean By default it is 

```
<requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
```

Without manifest file and **asInvoker** execution level your app will not be able to run updater without admin privileges on Windows.

**Comment by oaleynik** [comment]
@matthew-dean using https://github.com/akavel/rsrc you can compile your manifest file into .syso file, which then will be linked to Windows executable. I will add this to README - thanks!
